## NUMPY
The NumPy library is the core library for scientific computing in Python. 
It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a huge amount of high-level mathematical functions operate on these matrices and arrays.

In [1]:
#importing numpy
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# creating an array

NumPy allows you to create and operate on homogeneous multidimensional arrays faster than in standard Python.
ndarray (or its alias array) is NumPy's array class. A dimension is called an axis. 
In creating an array from scratch, 
<h4>we can use np.arange with the following syntax:</h4>

np.arange([start,] stop[, step,], dtype=None)

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,5)

array([1, 2, 3, 4])

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

In [5]:
n = np.array([1, 3, 5, 7])
n

array([1, 3, 5, 7])

In [6]:
type (n)

numpy.ndarray

In [7]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c   

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [9]:
 np.zeros((3,4)) #Create an array of zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [13]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [14]:
np.random.random((2,2)) #Create an array with random values


array([[0.32156295, 0.51132414],
       [0.50171548, 0.99360298]])

In [15]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## data types

In [16]:
np.dtype

numpy.dtype

In [17]:
b.dtype

dtype('float64')

In [18]:
c.dtype

dtype('float64')

## size 

In [19]:
b.size

6

In [20]:
c.size

12

In [21]:
e.size

4

In [22]:
f.size

4

### Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [23]:
a1 = np.arange(5)
b1 = np.array([2, 4, 0, 1, 2])
a1

array([0, 1, 2, 3, 4])

In [24]:
b1

array([2, 4, 0, 1, 2])

In [25]:
diff=a1-b1 #subtraction
diff

array([-2, -3,  2,  2,  2])

In [26]:
add=a1+b1 #addition
add

array([2, 5, 2, 4, 6])

In [27]:
div=a1/b1
div

array([0.  , 0.25,  inf, 3.  , 2.  ])

In [28]:
b1**2 #power function

array([ 4, 16,  0,  1,  4], dtype=int32)

In [29]:
2*a1 #multiply by 2

array([0, 2, 4, 6, 8])

In [30]:
np.sum(a1) # sum of the values

10

In [31]:
np.sin(a1)  #sin function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
np.exp(a1)  #exponential values

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
np.max(a1) #maximum value

4

In [34]:
np.min(a1) #minimum value

0

In [35]:
np.mean(a1) #finding mean

2.0

In [36]:
np.median(a1)  #finding median

2.0

In [37]:
np.sqrt(a1)  #square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [38]:
np.corrcoef(a1) #Correlation coefficient

1.0

## Reshaping Arrays

In [39]:
data = np.random.random((2,3))
data

array([[0.22301181, 0.68480203, 0.79414317],
       [0.27619753, 0.18565766, 0.56236761]])

In [40]:
np.reshape(data, (3,2))

array([[0.22301181, 0.68480203],
       [0.79414317, 0.27619753],
       [0.18565766, 0.56236761]])

In [41]:
np.reshape(data, (1,6))

array([[0.22301181, 0.68480203, 0.79414317, 0.27619753, 0.18565766,
        0.56236761]])

In [42]:
np.reshape(data, (6,1))

array([[0.22301181],
       [0.68480203],
       [0.79414317],
       [0.27619753],
       [0.18565766],
       [0.56236761]])

## Subsetting, Slicing, Indexing

### Subsetting
 

In [43]:
a1[2]    #Select the element at the 2nd index 3

2

In [44]:
b[1,2]   # Select the element at row 1 column 2

6.0

### Slicing

In [45]:
a1[0:2]  #Select items at index 0 and 1 

array([0, 1])

In [46]:
b[0:2,1]  #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [47]:
b[:1]  #Select all items at row 0 

array([[1.5, 2. , 3. ]])

In [48]:
c[1,...]   #Same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [49]:
a1[ : :-1]  #Reversed array a array([3, 2, 1])

array([4, 3, 2, 1, 0])

### boolean Indexing

In [50]:
a1[a1<2] #Select elements from a less than 2

array([0, 1])

In [51]:
arr1=np.arange(3)
arr1

array([0, 1, 2])

In [52]:
arr1[np.array([True, False,True])]

array([0, 2])

In [53]:
arr1=np.arange(10)
arr1[(arr1<5)|(arr1>7)]

array([0, 1, 2, 3, 4, 8, 9])

### Fancy Indexing

In [54]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [55]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation 

### Transposing Array


In [56]:
i = np.transpose(b) #Permute array dimensions
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [57]:
i.T #Permute array dimensions  

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Adding/Removing Elements

In [58]:
i.resize((2,3)) #Return a new array with shape (2,6)
i

array([[1.5, 3. , 5. ],
       [2. , 4. , 6. ]])

In [60]:
np.append(i,f) #Append items to an array


array([1.5, 3. , 5. , 2. , 4. , 6. , 1. , 0. , 0. , 1. ])

In [61]:
np.insert(a1, 1, 5) #Insert items in an array

array([0, 5, 1, 2, 3, 4])

In [62]:
np.delete(a1,[1])   #Delete items from an array

array([0, 2, 3, 4])

### Combining Arrays

In [63]:
np.concatenate((a1,b1),axis=0)    #Concatenate array

array([0, 1, 2, 3, 4, 2, 4, 0, 1, 2])

In [64]:
np.vstack((a1,b1))   #Stack arrays vertically (row-wise)

array([[0, 1, 2, 3, 4],
       [2, 4, 0, 1, 2]])

In [65]:
np.r_[e,f]    #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [66]:
np.hstack((e,f))    #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [67]:
np.column_stack((a1,b1))   #Create stacked column-wise arrays

array([[0, 2],
       [1, 4],
       [2, 0],
       [3, 1],
       [4, 2]])

In [68]:
np.c_[a1,b1]   #Create stacked column-wise arrays

array([[0, 2],
       [1, 4],
       [2, 0],
       [3, 1],
       [4, 2]])

### Splitting Arrays

In [69]:
np.hsplit(i,3) #Split the array horizontally at the 3rd

[array([[1.5],
        [2. ]]), array([[3.],
        [4.]]), array([[5.],
        [6.]])]

In [70]:
np.vsplit(c,2)   #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]